version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saadaswad
      POSTGRES_DB: myappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8080:8080"

  api:
    build: .
    container_name: my_dotnet_api
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: adminpass
      DB_NAME: myappdb
    ports:
      - "5000:8080"
    depends_on:
      - db

volumes:
  postgres_data:
