version: "3.8"

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src/API
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    command: bash -c "dotnet watch run --urls=http://0.0.0.0:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=host.docker.internal;Database=VexaFit;Username=postgres;Password=saadaswad
